### ISSUE TITLE
Congratulations on having pypi.org transferred to you!  When will you release 0.6.0+ to pypi.org?

### ISSUE THREAD

**Issue by PamelaM** [PennyDreadfulMTG/pystache#14]
Yes, I know, two days from getting ownership is no time at all for an open source project.

But I figure I could open the issue so that (a) You'd know that _someone_ is waiting for it and (b) you'd have the pleasure of _closing_ the issue when you complete your first pypi.org release!

Thank you for taking this project over.

**Comment by bakert** [comment]
v0.6.0 has now been published on pypi. https://github.com/PennyDreadfulMTG/pystache Wahoo!

**Comment by PamelaM** [comment]
Thank you!
