### ISSUE TITLE
Critical bug - python_requires missing from published releases

### ISSUE THREAD

**Issue by ITProKyle** [PennyDreadfulMTG/pystache#17]
The current releases of pystache on pypi are missing python version requirements resulting in it being installed by unsupported python versions. This is a major issue especially when dropping support for python versions like was done in 0.6.0.

This was identified by using [aws-cfn-bootstrap](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html) on older OS's (e.g. Ubuntu 16.04) which do not have python >= 3.6. Through the dependency chain it relies on this package but due to the missing python version requirement incompatible versions of pystache are being installed causing new EC2 instance bootstrapping to fail.

In addition to ensuring that a python version requirement be added to releases, would it be possible to yank the breaking release?

**Comment by bakert** [comment]
Thanks for the heads up Kyle. We dropped support for python 2.7 in the last release, as you noted.

Before releasing 0.6.0 we modified `setup.cfg` to specify `python_requires = >=3.6`. Although if I look at the releases on pypi it looks like no release (including 0.6.0) has a version specified. All past releases say "version None". 

<img width="1263" alt="Manage__pystache__–_release_version_0_5_4_·_PyPI" src="https://user-images.githubusercontent.com/1541/148256642-0da9ae33-13ef-4d69-bd25-e19700596941.png">

It's not clear to me what we're doing wrong (and that the package has always been doing wrong?) that is causing no version to be specified once the package gets to pypi. Tagging @sarnold who might understand this better than me.

**Comment by ITProKyle** [comment]
Ya, I saw the addition to `setup.cfg` and it looks correct to me. My guess would be that the version of setuptools being used is not respecting `python_requires` defined in the config file. But, the build-system.requirements _should_ sufficiently cover that. It's been a while since I have used `setup.py`/`setup.cfg` for projects so I'm not entirely sure.

The screenshot you shared isn't quite what I am referring to. The result of `python_requires` would be displayed in the metadata section of the pypi page. Example from one of my projects using poetry - https://github.com/onicagroup/runway/blob/v2.4.4/pyproject.toml#L31. Which results in the following:
![image](https://user-images.githubusercontent.com/23145462/148261147-390f9dae-446e-4169-89a7-9c06bdc7200a.png)

In the management page on pypi, python version for the tar.gz is the same as in your screenshot. It only shows `py3` for the wheel.
![image](https://user-images.githubusercontent.com/23145462/148261861-0e5e59a8-d85c-49bc-912f-f7df6be1e7eb.png)

**Comment by ITProKyle** [comment]
Actually, I may have jumped to my conclusion too soon. Inspecting the metadata files distributed with the pystache package, it does show `Requires-Python: >=3.6` - not sure why it's not displaying on PyPi. I revisited the error message provided to me and it looks like the issue may actually be related to pip. The version of pip they are using is 8.1.1. Looking through pip's changelog, it looks like the feature that uses `Requires-Python` was added in 9.0.0.

Gotta love supporting legacy systems...

**Comment by bakert** [comment]
Yikes. Let us know where you end up.

**Comment by sarnold** [comment]
The pip thing is a good catch; the usual "guidance" afaik is basically "always use the latest pip version" but I haven't dealt with pypi as a packager (mainly just Gentoo, .debs, yocto, etc, etc).  On the consumer side, your AWS workaround is probably using your own pystache dep with an older release.  That's about all I got for now...

**Comment by sarnold** [comment]
As "final" addendum, I guess `None` should be expected for a source package?  (whereas wheels are a different animal)
