### ISSUE TITLE
pystache.parser.ParsingError: Section end tag mismatch: each != each left

### ISSUE THREAD

**Issue by python345201067** [PennyDreadfulMTG/pystache#35]
<script id="left" type="text/x-handlebars-template">
        {{#each left}}
        <dd class="dis-item">
            <span class="person-name">{{passenger_name}}</span>
            <span class="person-card">{{passenger_id_no}}</span>
        </dd>
        {{/each}}
    </script>

**Comment by python345201067** [comment]
```

<script id="left" type="text/x-handlebars-template">
        {{#each left}}
        <dd class="dis-item">
            <span class="person-name">{{passenger_name}}</span>
            <span class="person-card">{{passenger_id_no}}</span>
        </dd>
        {{/each}}
    </script>
```

**Comment by bakert** [comment]
I'm not sure what this is but as this appears to be a bot and this library is a Mustache library not a Handlebars library I'm closing this.
