### ISSUE TITLE
Add a tag on the current version until #5 gets addressed

### ISSUE THREAD

**Issue by hategan** [PennyDreadfulMTG/pystache#8]
I'm using pystache in a project and have run into the setuptools issue with the original version. I appreciate your effort to take over the pystache pypi. However, while that process unfolds, it would be nice if I could still refer to a somewhat immutable version of the code, so adding a tag to this fork would be helpful.

**Comment by bakert** [comment]
@hategan @bgermann @chrismheiser we now have a v0.6.0 release here – https://github.com/PennyDreadfulMTG/pystache/releases/tag/v0.6.0
